# Generated by Django 4.2.7 on 2023-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tokentoconfirmemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='tokentoconfirmemail',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
