# Generated by Django 4.2.7 on 2023-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verificated',
        ),
        migrations.AddField(
            model_name='tokentoconfirmemail',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tokentoconfirmemail',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
