# Generated by Django 4.2 on 2023-10-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.AlterField(
            model_name='popularproduct',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.product'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.customuser'),
        ),
    ]
