# Generated by Django 4.2 on 2023-10-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_cartproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularproduct',
            old_name='name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderlist',
        ),
    ]
