# Generated by Django 4.1 on 2023-11-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_order_comment_order_delivery_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
