# Generated by Django 4.1 on 2023-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_order_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='order',
            name='lng',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
