# Generated by Django 4.2.7 on 2023-12-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_alter_cartproduct_order_alter_cartproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
