# Generated by Django 4.2.7 on 2023-12-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_alter_popularproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproduct',
            options={'ordering': ['-code']},
        ),
    ]
