# Generated by Django 4.2.7 on 2023-12-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_alter_popularproduct_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='curent_date',
            new_name='date',
        ),
    ]
