# Generated by Django 4.2.7 on 2023-12-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_alter_order_options_alter_order_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id', '-date']},
        ),
    ]
