# Generated by Django 4.2.7 on 2023-12-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_remove_cartproduct_product_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
