# Generated by Django 4.2.7 on 2023-12-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_remove_cartproduct_price_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.product'),
        ),
    ]
