errors = {
    "incorrect_login_args": "the username or password is incorrect",
    "username_alredy_exists": "a user with this username already exists",
    "email_alredy_exists": "a user with this email already exists",
    "incorrect_emial_code": "incorrect code",
    "reset_link_expired": "The link has expired for 1 hour. Try to request password recovery again",
    "reset_link_invalid": "the password reset link is invalid",
    "users_email_not_exist": "There is no user with such an email",
    "reset_link_already_sent": "you have already received an email to reset your password",
    "confirm_email_incorrect_url": "Incorrect url adress",
    "confirm_link_expired": "You take too long to confirm the email. Try to register again",
    "empty_username": "Write your name",
    "incorrect_phone": "Write correct phone number",
    "incorrect_adress": "Write correct adress",
    "incorrect_email": "write correct email",
    "empty_payment_method": "Chose payment method",
    "empty_delivery_method": "Chose delivery method",
    "different_passwords": "the entered passwords do not match",
}
